local board = require("board")
local config = require("config")
local helper = require("spec.spec_helper")

local function new_board()
	return board.new()
end

local function place_stone(b, row, col, color)
	b[row][col] = board.make_stone(color, "stone_basic")
end

describe("Territory scoring", function()
	it("assigns neutral on equal nearest eligible distance tie", function()
		local b = new_board()
		place_stone(b, 3, 2, config.STONE_BLACK)
		place_stone(b, 2, 3, config.STONE_WHITE)
		local territory = helper.territory_map(b)
		assert.are.equal(config.STONE_NONE, territory[2][2])
	end)

	it("ignores outside candidates farther from center than target point", function()
		local b = new_board()
		place_stone(b, 1, 1, config.STONE_BLACK)
		place_stone(b, 3, 3, config.STONE_WHITE)
		local territory = helper.territory_map(b)
		assert.are.equal(config.STONE_WHITE, territory[2][2])
	end)

	it("does not apply global fallback from ineligible stones", function()
		local b = new_board()
		place_stone(b, 1, 1, config.STONE_BLACK)
		local territory = helper.territory_map(b)
		assert.are.equal(config.STONE_NONE, territory[2][2])
	end)

	it("limits stone influence to the nearest-corner rectangle", function()
		local b = new_board()
		place_stone(b, 3, 3, config.STONE_BLACK)
		local territory = helper.territory_map(b)
		assert.are.equal(config.STONE_NONE, territory[2][5])
	end)

	it("prevents black enclosure claims when region touches opponent stones", function()
		local b = new_board()
		place_stone(b, 4, 5, config.STONE_BLACK)
		place_stone(b, 5, 4, config.STONE_BLACK)
		place_stone(b, 5, 6, config.STONE_BLACK)
		place_stone(b, 6, 5, config.STONE_WHITE)
		local territory = helper.territory_map(b)
		assert.is_true(territory[5][5] ~= config.STONE_BLACK)
	end)

	it("treats opponent stones as barriers during empty-region enclosure traversal", function()
		local b = new_board()
		place_stone(b, 4, 4, config.STONE_BLACK)
		place_stone(b, 4, 6, config.STONE_BLACK)
		place_stone(b, 6, 4, config.STONE_BLACK)
		place_stone(b, 6, 6, config.STONE_BLACK)
		place_stone(b, 5, 4, config.STONE_WHITE)
		local territory = helper.territory_map(b)
		assert.is_true(territory[5][5] ~= config.STONE_BLACK)
	end)

	it("maps territory counts directly to point totals", function()
		local b = new_board()
		place_stone(b, 3, 2, config.STONE_BLACK)
		place_stone(b, 2, 3, config.STONE_WHITE)
		local territory = helper.territory_map(b)
		local black_points = helper.territory_points(territory, config.STONE_BLACK)
		local white_points = helper.territory_points(territory, config.STONE_WHITE)
		assert.are.equal(black_points, helper.liberty_points(b, config.STONE_BLACK))
		assert.are.equal(white_points, helper.liberty_points(b, config.STONE_WHITE))
	end)
end)
