--- Unified card definitions.
--- Source of truth for all card content.
--- @module objects.definitions.cards

local M = {
	card_point_tap = {
		id = "card_point_tap",
		type = "card",
		name = "Point Tap",
		description = "Gain 2 points immediately.",
		display_name = "Point Tap",
		rarity = "common",
		probability = 1.0,
		cost = 1,
		energy_cost = 1,
		effects = { { effect_name = "add_points", phase = "points", value = 2, priority = 10 } },
	},
	card_point_push = {
		id = "card_point_push",
		type = "card",
		name = "Point Push",
		description = "Gain 4 points immediately.",
		display_name = "Point Push",
		rarity = "uncommon",
		probability = 0.8,
		cost = 2,
		energy_cost = 2,
		effects = { { effect_name = "add_points", phase = "points", value = 4, priority = 10 } },
	},
	card_small_mult = {
		id = "card_small_mult",
		type = "card",
		name = "Small Mult",
		description = "Gain 1 multiplier immediately.",
		display_name = "Small Mult",
		rarity = "common",
		probability = 1.0,
		cost = 1,
		energy_cost = 1,
		effects = { { effect_name = "add_mult", phase = "mult", value = 1, priority = 10 } },
	},
	card_big_mult = {
		id = "card_big_mult",
		type = "card",
		name = "Big Mult",
		description = "Gain 2 multiplier immediately.",
		display_name = "Big Mult",
		rarity = "uncommon",
		probability = 0.8,
		cost = 2,
		energy_cost = 2,
		effects = { { effect_name = "add_mult", phase = "mult", value = 2, priority = 10 } },
	},
	card_balanced_boost = {
		id = "card_balanced_boost",
		type = "card",
		name = "Balanced Boost",
		description = "Gain 2 points and 1 multiplier.",
		display_name = "Balanced Boost",
		rarity = "rare",
		probability = 0.6,
		cost = 2,
		energy_cost = 2,
		effects = {
			{ effect_name = "add_points", phase = "points", value = 2, priority = 10 },
			{ effect_name = "add_mult", phase = "mult", value = 1, priority = 10 },
		},
	},
	card_steel = {
		id = "card_steel",
		type = "card",
		name = "Steel",
		description = "A steel card with no immediate effects.",
		display_name = "Steel",
		rarity = "common",
		probability = 1.0,
		cost = 1,
		energy_cost = 1,
		tags = { "steel" },
		effects = {},
	},
	card_focus_stance = {
		id = "card_focus_stance",
		type = "card",
		name = "Focus Stance",
		description = "Creates a temporary +5 points stance for 3 rounds.",
		display_name = "Focus Stance",
		rarity = "rare",
		probability = 0.6,
		cost = 2,
		energy_cost = 2,
		tags = {},
		effects = {
			{ effect_name = "create_temporary_stance", phase = "points", value = { stance_id = "stance_focus_bonus", rounds = 3, points = 5 }, priority = 5 },
		},
	},
	card_destroy_enemy_stone = {
		id = "card_destroy_enemy_stone",
		type = "card",
		name = "Shatter Mark",
		description = "Target an enemy stone. Destroy it with 1/4 chance.",
		display_name = "Shatter Mark",
		rarity = "rare",
		probability = 0.5,
		cost = 2,
		energy_cost = 2,
		targeting = { kind = "board_stone", rule = "enemy" },
		effects = {
			{
				effect_name = "destroy_selected_enemy_stone",
				phase = "points",
				value = { chance_numerator = 1, chance_denominator = 4 },
				priority = 10,
				conditions = {
					{ condition_name = "selected_target_exists" },
					{ condition_name = "selected_target_is_enemy_stone" },
				},
			},
		},
	},
	card_forge_mark = {
		id = "card_forge_mark",
		type = "card",
		name = "Forge Mark",
		description = "Target a friendly board stone. Permanently add +10 points for this game.",
		display_name = "Forge Mark",
		rarity = "rare",
		probability = 0.5,
		cost = 2,
		energy_cost = 2,
		targeting = { kind = "board_stone", rule = "friendly" },
		effects = {
			{
				effect_name = "add_permanent_points_to_selected_stone",
				phase = "points",
				value = { points = 10 },
				priority = 10,
				conditions = {
					{ condition_name = "selected_target_exists" },
					{ condition_name = "selected_target_is_friendly_stone" },
				},
			},
		},
	},
}

return M
